version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ft123456
      MYSQL_DATABASE: flash_sale
      MYSQL_USER: finntew
      MYSQL_PASSWORD: finn123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: finntew
      RABBITMQ_DEFAULT_PASS: ft123456
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # HTTP management UI

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9898:80"
      - "443:443"

  flask_app_1:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  flask_app_2:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5002:5000"

  flask_app_3:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5003:5000"


volumes:
  mysql_data:
  redis_data:
  rabbitmq_data: